cache: bundler
sudo: false
language: ruby
dist: bionic
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - jruby-head
addons:
  apt:
    packages:
      - libgeos-c1v5
before_install:
- gem update --system
- gem install bundler
