cache: bundler
sudo: false
language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - rbx-3
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-19mode
addons:
  apt:
    packages:
      - libgeos-c1
