cache: bundler
sudo: false
language: ruby
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - jruby-head
addons:
  apt:
    packages:
      - libgeos-c1
before_install:
- gem update --system
- gem install bundler
